spring.application.name=passro-backend

# Import .env file
spring.config.import=optional:file:.env[.properties]

# Database Settings
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging Settings
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.com.cupid.qufit=DEBUG

# SMTP Settings
# SMTP 서버 호스트
spring.mail.host=smtp.gmail.com
# SMTP 서버 포트
spring.mail.port=587
# SMTP 서버 로그인 아이디
spring.mail.username=wjddydghks0801
# SMTP 서버 로그인 비밀번호
spring.mail.password=lcqaecoopjfrtggi
# 사용자 인증 시도 여부
spring.mail.properties.mail.smtp.auth=true
# STARTTLS 사용 여부
spring.mail.properties.mail.smtp.starttls.enable=true

# Server Settings
server.port=8080

# Timezone Setting
spring.jackson.time-zone=Asia/Seoul

# S3 Settings
aws.s3.bucket=${AWS_S3_BUCKET:}
aws.s3.region=${AWS_REGION:ap-northeast-2}
aws.s3.endpoint=${AWS_S3_ENDPOINT:}
aws.s3.access-key=${AWS_ACCESS_KEY_ID:}
aws.s3.secret-key=${AWS_SECRET_ACCESS_KEY:}
aws.s3.path-style-access-enabled=${AWS_S3_PATH_STYLE:true}
>>>>>>> origin/main
